language: python
sudo: false
python:
    - "2.7"
virtualenv:
    system_site_packages: true
before_install:
    - pip install numpy
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install javabridge python-bioformats

script:
    - python setup.py install
    - rm -rf build
    - py.test

after_success:
    - coveralls
